function edgs = edges_mine( DT )
% Find edges indexes from a triangluation. Implemented by hand because the
% official Matlab implementation only works for 2024a or better.

edgs = unique( [ ...
  DT.Faces(:,1), DT.Faces(:,2); ...
  DT.Faces(:,1), DT.Faces(:,3); ...
  DT.Faces(:,2), DT.Faces(:,3); ...
  ],'rows');

end